# Generated by Django 6.1 on 2026-08-14 16:19

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Gift",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=200, verbose_name="Название")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                ("price", models.PositiveIntegerField(default=0, verbose_name="Цена в монетах")),
                (
                    "required_spins",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Необходимо спинов для бесплатного получения"
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=0, verbose_name="Количество доступных"),
                ),
            ],
            options={
                "verbose_name": "Подарок",
                "verbose_name_plural": "Подарки",
            },
        ),
        migrations.CreateModel(
            name="GiftPurchase",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "payment_type",
                    models.CharField(
                        choices=[("currency", "За монеты"), ("spins", "За спины")],
                        max_length=10,
                        verbose_name="Тип оплаты",
                    ),
                ),
                (
                    "gift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchases",
                        to="gifts.gift",
                        verbose_name="Подарок",
                    ),
                ),
            ],
            options={
                "verbose_name": "Покупка подарка",
                "verbose_name_plural": "Покупки подарков",
            },
        ),
    ]
