# Generated by Django 6.1 on 2026-08-30 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0004_alter_gift_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='gifts/', verbose_name='Картинка подарка'),
        ),
    ]
