repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: detect-private-key

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.4
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        additional_dependencies:
          - django==6.1
          - djangorestframework==3.18.0
          - django-environ==0.11.2
          - psycopg[binary]==3.2.3
          - django-stubs==6.1.0
          - djangorestframework-stubs==3.18.0
          - djangorestframework-simplejwt
          - drf_spectacular
          - daphne
        args: [--config-file=pyproject.toml]
